name: "Test"

on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Test Local Action"
        id: test
        #uses: ./.github/mirror-repository-action/
        #uses: ./.github/mirror-repository-action/
        uses: smashedr/mirror-repository-action@master
        with:
          url: https://codeberg.org/shaner/codeberg-mirror
          #host: https://codeberg.org
          #owner: shaner
          #repo: private
          username: shaner
          password: ${{ secrets.CODEBERG_TOKEN }}
